/**
 * Type definitions for structured insights generated by the CodeWriterAgent
 */

export type InsightType =
  | 'statistic' // Single numeric value or metric
  | 'ranking' // Top N list
  | 'timeline' // Time-series data
  | 'comparison' // Before/after or A vs B comparison
  | 'distribution' // Breakdown by category
  | 'achievement'; // Milestone or accomplishment

export type InsightCategory =
  | 'music'
  | 'fitness'
  | 'social'
  | 'productivity'
  | 'entertainment'
  | 'general';

/**
 * Base insight interface - all insights must conform to this structure
 */
export interface Insight {
  id: string; // Unique identifier (e.g., "total-listens", "top-artists")
  type: InsightType;
  category: InsightCategory;
  title: string; // User-facing title
  value: unknown; // Type-specific value structure
  metadata?: {
    unit?: string; // e.g., "minutes", "km", "songs"
    timeframe?: string; // e.g., "2024", "Last 30 days"
    source?: string; // e.g., "StreamingHistory.csv"
    confidence?: number; // 0-1 confidence score if applicable
    [key: string]: unknown; // Allow additional metadata
  };
}

/**
 * Statistic insight value - a single number with optional comparison
 */
export interface StatisticValue {
  number: number;
  label?: string; // Additional label (e.g., "hours", "songs")
  comparison?: {
    previous: number;
    change: number;
    changePercent: number;
  };
}

/**
 * Ranking insight value - an ordered list
 */
export interface RankingValue {
  items: Array<{
    rank: number;
    name: string;
    value: number;
    metadata?: Record<string, unknown>;
  }>;
}

/**
 * Timeline insight value - time-series data points
 */
export interface TimelineValue {
  dataPoints: Array<{
    timestamp: string | Date;
    value: number;
    label?: string;
  }>;
}

/**
 * Comparison insight value - two values being compared
 */
export interface ComparisonValue {
  current: {
    label: string;
    value: number;
  };
  previous: {
    label: string;
    value: number;
  };
  change: number;
  changePercent: number;
}

/**
 * Distribution insight value - breakdown by categories
 */
export interface DistributionValue {
  categories: Array<{
    name: string;
    value: number;
    percentage: number;
  }>;
  total?: number;
}

/**
 * Achievement insight value - a milestone or accomplishment
 */
export interface AchievementValue {
  achieved: boolean;
  description: string;
  progress?: number; // 0-1 progress if not yet achieved
  milestone?: number; // The target value
  current?: number; // Current value towards milestone
}

/**
 * Type guard to check if an object is a valid Insight
 */
export function isInsight(obj: unknown): obj is Insight {
  if (!obj || typeof obj !== 'object') return false;

  const insight = obj as Insight;

  return (
    typeof insight.id === 'string' &&
    typeof insight.type === 'string' &&
    ['statistic', 'ranking', 'timeline', 'comparison', 'distribution', 'achievement'].includes(
      insight.type
    ) &&
    typeof insight.category === 'string' &&
    ['music', 'fitness', 'social', 'productivity', 'entertainment', 'general'].includes(
      insight.category
    ) &&
    typeof insight.title === 'string' &&
    insight.value !== undefined
  );
}

/**
 * Validates an array of insights
 */
export function validateInsights(insights: unknown): insights is Insight[] {
  if (!Array.isArray(insights)) return false;
  return insights.every(isInsight);
}

/**
 * Type guard for StatisticValue
 */
export function isStatisticValue(value: unknown): value is StatisticValue {
  if (!value || typeof value !== 'object') return false;
  const stat = value as StatisticValue;
  return typeof stat.number === 'number';
}

/**
 * Type guard for RankingValue
 */
export function isRankingValue(value: unknown): value is RankingValue {
  if (!value || typeof value !== 'object') return false;
  const ranking = value as RankingValue;
  return (
    Array.isArray(ranking.items) &&
    ranking.items.every(
      (item) =>
        typeof item.rank === 'number' &&
        typeof item.name === 'string' &&
        typeof item.value === 'number'
    )
  );
}

/**
 * Type guard for TimelineValue
 */
export function isTimelineValue(value: unknown): value is TimelineValue {
  if (!value || typeof value !== 'object') return false;
  const timeline = value as TimelineValue;
  return (
    Array.isArray(timeline.dataPoints) &&
    timeline.dataPoints.every(
      (point) =>
        (typeof point.timestamp === 'string' || point.timestamp instanceof Date) &&
        typeof point.value === 'number'
    )
  );
}

/**
 * Type guard for DistributionValue
 */
export function isDistributionValue(value: unknown): value is DistributionValue {
  if (!value || typeof value !== 'object') return false;
  const dist = value as DistributionValue;
  return (
    Array.isArray(dist.categories) &&
    dist.categories.every(
      (cat) =>
        typeof cat.name === 'string' &&
        typeof cat.value === 'number' &&
        typeof cat.percentage === 'number'
    )
  );
}
